#include "SpriteTools.h"

//presets of PIXEL_COLORED
const CHAR_INFO PIXEL = PIXEL_COLORED(BACKGROUND_WHITE);
const CHAR_INFO& PIXEL_ON = PIXEL;
const CHAR_INFO PIXEL_OFF = PIXEL_COLORED(BACKGROUND_BLACK);
