#ifndef _GAME_STATES_H_
#define _GAME_STATES_H_

enum E_GAME_STATE
{
	//THE FIRST MENU SEEN
	E_GAME_STATE_MAIN_MENU,


	// WHEN YOU'RE ACTURALLYB PLAYING THE GAME
	E_GAME_STATE_IN_GAME,

	//WHEN THE GAME IS PAUSED
	E_GAME_STATE_PAUSE_MENU,

	// WHEN THE GAME IS LOST
	E_GAME_STATE_LOSE_GAME,

	//WHEN THE GAME IS BEATEN
	E_GAME_STATE_WIN_GAME,

	//SOMETHING INTERESTING FOR PEOPLE WHO DONT WANT TO PLAY AND JUST WANT TO WATCH A MENU SCREEN
	E_GAME_STATE_DEMO_GAME
};

#endif
